allowBuilds:
  esbuild: false
  sharp: false
  workerd: false
minimumReleaseAgeExclude:
  - '@cloudflare/workerd-darwin-64@1.20260526.1'
  - '@cloudflare/workerd-darwin-arm64@1.20260526.1'
  - '@cloudflare/workerd-linux-64@1.20260526.1'
  - '@cloudflare/workerd-linux-arm64@1.20260526.1'
  - '@cloudflare/workerd-windows-64@1.20260526.1'
  - miniflare@4.20260526.0
  - workerd@1.20260526.1
  - wrangler@4.95.0
